## -*- texinfo -*-
## @deftypefn {Function File} {} maximaFromFile (@var{file}, @var{cmd1}, @var{cmd2}, @dots{})
## Return a string with the result generated by Maxima in response of executing
## the file @var{file} and commands @var{cmd1}, @var{cmd2}, @dots{} 
## The first argument is a Maxima file, this file must exist in one 
## directory registered in the Maxima variable "file_search_maxima".
## All other arguments are Maxima command.
##
## Example:
## @example
## maximaFromFile("test.mac", "func1()", "diff(x^3+3*x^2+sin(x),x)")
## @end example
## In this example "func1()" must be defined in the file "test.mac"
##
## @seealso{maxima2sym, maxima2str, maxima2num}
## @end deftypefn

## Author: Leansy Alfonso Pérez <leansy@uci.cu>
## Created: February 2009

function result=maximaFromFile(varargin)
	n = length(varargin);
	retult = "";
	if(n == 0)
		error ("maximaFromFile: expecting \"File\" argument");
		return;
	endif
    __maxima_utils;
    load_file = sprintf("load(\\\"%s\\\")", varargin{1});
    varargin{1} = load_file;
    result = __maxima2str(varargin{:});
endfunction
