## -*- texinfo -*-
## @deftypefn {Function File} {} maxima2str (@var{cmd1}, @var{cmd2}, @dots{})
## Return a string with the result generated by Maxima in response to 
## commands @var{cmd1}, @var{cmd2}, @dots{} 
## All arguments are Maxima command.
##
## Example:
## @example
## y=maxima2str("diff(x^3+3*x^2+sin(x),x)")
## 
## @result{} y = cos(x)+3*x^2+6*x
## @end example
## In this example the class of "y" is "char"
##
## @seealso{maxima2sym, maximaFromFile, maxima2num}
## @end deftypefn

## Author: Leansy Alfonso Pérez <leansy@uci.cu>
## Created: February 2009

function result=maxima2str(varargin)
    __maxima_utils;
    result = __maxima2str(varargin{:});
endfunction
