## -*- texinfo -*-
## @deftypefn {Function File} {} maxima2sym (@var{cmd}, @dots{})
## Return a symbolic expression generated by Maxima corresponding
## to the result of the Maxima command @var{cmd}. All others 
## arguments are octave symbolics variables presented in the 
## result expression.
##
## Example:
## @example
## x=sym("x");
## y=maxima2sym("diff(x^3+3*x^2+sin(x),x)",x)
## 
## @result{} y = (3.0)*x^(2.0)+cos(x)+(6.0)*x
## @end example
## In this example the class of "y" is "sym"
##
## @seealso{maxima2str, maximaFromFile}
## @end deftypefn

## Author: Leansy Alfonso Pérez <leansy@uci.cu>
## Created: February 2009

function result = maxima2sym(varargin)
    __maxima_utils;
    result = __maxima2sym(varargin{:});
endfunction

#export LD_PRELOAD="/usr/lib/libginac-1.4.so.0"
#addpath (genpath ("path_to_dir"), "-begin");
